name       : haskell-stack
version    : 2.1.3.1
release    : 4
source     :
    - https://hackage.haskell.org/package/stack-2.1.3.1/stack-2.1.3.1.tar.gz : f983369a22a3e3af9ae09770cf34e4ba439cc7f5ef5a0e87f4db11c1ec5356e0
license    : BSD-3-Clause
component  : programming.haskell
summary    : Stack is a cross-platform program for developing Haskell projects
description: |
    Stack is a cross-platform program for developing Haskell projects
builddeps  :
    - haskell-bindings-uname-devel
    - haskell-cabal-install
    - haskell-echo-devel
    - haskell-extra-devel
    - haskell-file-embed-devel
    - haskell-fsnotify-devel
    - haskell-hi-file-parser-devel
    - haskell-mintty-devel
    - haskell-mustache-devel
    - haskell-neat-interpolation-devel
    - haskell-open-browser-devel
    - haskell-optparse-applicative-devel
    - haskell-optparse-simple-devel
    - haskell-pantry-devel
    - haskell-project-template-devel
    - haskell-regex-applicative-text-devel
    - haskell-store-devel
    - haskell-terminal-size-devel
    - haskell-unicode-transforms-devel
networking : yes
setup      : |
    %cabal_configure --dynlibdir="\$libdir/\$compiler/\$pkgid"
build      : |
    %cabal_build
install    : |
    %cabal_install
