name       : haskell-stack
version    : 1.3.2
release    : 1
source     :
    - http://hackage.haskell.org/package/stack-1.3.2/stack-1.3.2.tar.gz : 488b9292ea605c92f6ebf79b233e8e374d857b21053051cb44b305dad8f0d3f7
license    : BSD-3-Clause
component  : programming.haskell
summary    : Stack is a cross-platform program for developing Haskell projects
description: |
    Stack is a cross-platform program for developing Haskell projects
builddeps  :
    - ghc-devel
    - haskell-annotated-wl-pprint
    - haskell-base16-bytestring
    - haskell-binary-tagged
    - haskell-cabal-install
    - haskell-cryptohash-conduit
    - haskell-errors
    - haskell-extra
    - haskell-fail
    - haskell-file-embed
    - haskell-filelock
    - haskell-fsnotify
    - haskell-generic-deriving
    - haskell-hastache
    - haskell-http-conduit
    - haskell-hit
    - haskell-hpack
    - haskell-lifted-async
    - haskell-monad-unlift
    - haskell-nats
    - haskell-open-browser
    - haskell-optparse-simple
    - haskell-path-io
    - haskell-persistent-sqlite
    - haskell-persistent-template
    - haskell-pid1
    - haskell-project-template
    - haskell-regex-applicative-text
    - haskell-retry
    - haskell-safe-exceptions
    - haskell-store
    - haskell-text-binary
    - haskell-text-metrics
    - haskell-unicode-transforms
    - haskell-vector-binary-instances
    - haskell-zip-archive
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
