name       : haskell-stack
version    : 1.6.5
release    : 2
source     :
    - http://hackage.haskell.org/package/stack-1.6.5/stack-1.6.5.tar.gz : ee5c8ca3f9ee81d1bde3ff54ca07f902a98476f4804f0cf7002b56deed07aa38
license    : BSD-3-Clause
component  : programming.haskell
summary    : Stack is a cross-platform program for developing Haskell projects
description: |
    Stack is a cross-platform program for developing Haskell projects
builddeps  :
    - ghc-devel
    - haskell-annotated-wl-pprint
    - haskell-base16-bytestring
    - haskell-binary-tagged
    - haskell-bindings-uname
    - haskell-cabal-install
    - haskell-cryptohash-conduit
    - haskell-cryptonite-conduit
    - haskell-errors
    - haskell-echo
    - haskell-extra
    - haskell-file-embed
    - haskell-filelock
    - haskell-fsnotify
    - haskell-generic-deriving
    - haskell-hackage-security
    - haskell-hastache
    - haskell-http-conduit
    - haskell-hit
    - haskell-hpack
    - haskell-lifted-async
    - haskell-microlens-mtl
    - haskell-mintty
    - haskell-monad-unlift
    - haskell-neat-interpolation
    - haskell-open-browser
    - haskell-optparse-simple
    - haskell-path-io
    - haskell-persistent-sqlite
    - haskell-persistent-template
    - haskell-pid1
    - haskell-project-template
    - haskell-regex-applicative-text
    - haskell-retry
    - haskell-rio
    - haskell-safe-exceptions
    - haskell-store
    - haskell-tar
    - haskell-text-binary
    - haskell-text-metrics
    - haskell-unicode-transforms
    - haskell-vector-binary-instances
    - haskell-zip-archive
networking : yes
setup      : |
    %cabal_configure --dynlibdir="\$libdir/\$compiler/\$pkgid"
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
